/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.vistas.panelBuscar;
import app.vistas.panelBienvenida;
import app.vistas.panelRegistro;
import app.vistas.panelReportes;
import app.vistas.panelAdministrar;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.Usuario;

/**
 *
 * @author francisco
 */
public class Principal extends javax.swing.JFrame {

    private int xcord = 0;
    private int ycord = 0;
    private Usuario usuario;

    private final Color COLOR_USUARIO;
    private final Color COLOR_ADMINISTRADOR;
    private Color COLOR;

    /**
     * Creates new form Principal
     *
     * @param usuario
     * @throws java.sql.SQLException
     */
    public Principal(Usuario usuario) throws SQLException {
        this.usuario = usuario;
       
        this.COLOR_USUARIO = new Color(0, 153, 255);
        this.COLOR_ADMINISTRADOR = new Color(255, 51, 0);

        initComponents();
        initPrincipal();
        cerrar();
    }

    private void validarTipoUsuario() {
        if (usuario.getTipo().equals("Usuario")) {
            btnOpcionAdministrar.setVisible(false);
            infoColorUsario.setBackground(COLOR_USUARIO); // Cambiar a color azul            
            btnOpcionInicio.setForeground(COLOR_USUARIO);            
            COLOR = COLOR_USUARIO;
        } else {
            btnOpcionAdministrar.setVisible(true);
            infoColorUsario.setBackground(COLOR_ADMINISTRADOR); // Cambiar a color rojo  
            btnOpcionInicio.setForeground(COLOR_ADMINISTRADOR);            
            COLOR = COLOR_ADMINISTRADOR;
        }
    }

    private void initPrincipal() throws SQLException {
        validarTipoUsuario();
        btnOpcionInicio.setBackground(COLOR);

        //Vista por defecto
        mainViewFrame.removeAll();
        mainViewFrame.add(new panelBienvenida());
        mainViewFrame.validate();
    }

    private void cerrar() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                confirmarSalida(false);
            }
        });
        this.setVisible(true);

    }

    private void confirmarSalida(boolean CERRAR_APLICACION) {
        int valor = JOptionPane.showConfirmDialog(this, "¿ESTA SEGURO QUE DESEA SALIR?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (valor == JOptionPane.YES_NO_OPTION) {
            if (CERRAR_APLICACION) {
                System.exit(0);
            } else {
                Login l = new Login();
                l.setVisible(true);
                dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainViewFrame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnOpcionInicio = new javax.swing.JButton();
        infoColorUsario = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        btnOpcionRegistro = new javax.swing.JButton();
        btnOpcionBuscar = new javax.swing.JButton();
        btnOpcionReporte = new javax.swing.JButton();
        btnOpcionAdministrar = new javax.swing.JButton();
        btnCerrarAplicacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 670));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainViewFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 850, 640));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcionInicio.setForeground(new java.awt.Color(0, 153, 255));
        btnOpcionInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicioIcon.png"))); // NOI18N
        btnOpcionInicio.setText("INICIO");
        btnOpcionInicio.setBorderPainted(false);
        btnOpcionInicio.setContentAreaFilled(false);
        btnOpcionInicio.setFocusPainted(false);
        btnOpcionInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcionInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        infoColorUsario.setBackground(new java.awt.Color(0, 153, 255));
        infoColorUsario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoutIcon.png"))); // NOI18N
        btnCerrarSesion.setText("SALIR");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        infoColorUsario.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(infoColorUsario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 150, 46));

        btnOpcionRegistro.setBackground(new java.awt.Color(51, 51, 51));
        btnOpcionRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcionRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarIcon.png"))); // NOI18N
        btnOpcionRegistro.setText("REGISTRO");
        btnOpcionRegistro.setBorderPainted(false);
        btnOpcionRegistro.setContentAreaFilled(false);
        btnOpcionRegistro.setFocusPainted(false);
        btnOpcionRegistro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcionRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, -1));

        btnOpcionBuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnOpcionBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcionBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarIcon.png"))); // NOI18N
        btnOpcionBuscar.setText("BUSCAR");
        btnOpcionBuscar.setBorderPainted(false);
        btnOpcionBuscar.setContentAreaFilled(false);
        btnOpcionBuscar.setFocusPainted(false);
        btnOpcionBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, -1));

        btnOpcionReporte.setBackground(new java.awt.Color(51, 51, 51));
        btnOpcionReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcionReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteIcon.png"))); // NOI18N
        btnOpcionReporte.setText("REPORTES");
        btnOpcionReporte.setBorderPainted(false);
        btnOpcionReporte.setContentAreaFilled(false);
        btnOpcionReporte.setFocusPainted(false);
        btnOpcionReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcionReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, -1));

        btnOpcionAdministrar.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcionAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioIcon.png"))); // NOI18N
        btnOpcionAdministrar.setText("ADMINISTRAR");
        btnOpcionAdministrar.setBorderPainted(false);
        btnOpcionAdministrar.setContentAreaFilled(false);
        btnOpcionAdministrar.setHideActionText(true);
        btnOpcionAdministrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcionAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionAdministrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 670));

        btnCerrarAplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarIcon.png"))); // NOI18N
        btnCerrarAplicacion.setBorderPainted(false);
        btnCerrarAplicacion.setContentAreaFilled(false);
        btnCerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarAplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionInicioActionPerformed
        btnOpcionInicio.setForeground(COLOR);
        btnOpcionRegistro.setForeground(Color.WHITE);
        btnOpcionBuscar.setForeground(Color.WHITE);
        btnOpcionReporte.setForeground(Color.WHITE);
        btnOpcionAdministrar.setForeground(Color.WHITE);

        mainViewFrame.removeAll();
        try {
            mainViewFrame.add(new panelBienvenida());
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainViewFrame.validate();
    }//GEN-LAST:event_btnOpcionInicioActionPerformed

    private void btnOpcionRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionRegistroActionPerformed
        btnOpcionRegistro.setForeground(COLOR);
        btnOpcionInicio.setForeground(Color.WHITE);
        btnOpcionBuscar.setForeground(Color.WHITE);
        btnOpcionReporte.setForeground(Color.WHITE);
        btnOpcionAdministrar.setForeground(Color.WHITE);

        mainViewFrame.removeAll();
        mainViewFrame.add(new panelRegistro(usuario));
        mainViewFrame.validate();
    }//GEN-LAST:event_btnOpcionRegistroActionPerformed

    private void btnOpcionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionBuscarActionPerformed
        btnOpcionBuscar.setForeground(COLOR);
        btnOpcionRegistro.setForeground(Color.WHITE);
        btnOpcionInicio.setForeground(Color.WHITE);
        btnOpcionReporte.setForeground(Color.WHITE);
        btnOpcionAdministrar.setForeground(Color.WHITE);

        mainViewFrame.removeAll();
        mainViewFrame.add(new panelBuscar());
        mainViewFrame.validate();

    }//GEN-LAST:event_btnOpcionBuscarActionPerformed

    private void btnOpcionReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionReporteActionPerformed
        btnOpcionReporte.setForeground(COLOR);
        btnOpcionBuscar.setForeground(Color.WHITE);
        btnOpcionRegistro.setForeground(Color.WHITE);
        btnOpcionInicio.setForeground(Color.WHITE);
        btnOpcionAdministrar.setForeground(Color.WHITE);

        mainViewFrame.removeAll();
        mainViewFrame.add(new panelReportes());
        mainViewFrame.validate();
    }//GEN-LAST:event_btnOpcionReporteActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        confirmarSalida(false);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xcord = evt.getX();
        ycord = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xcord, y - ycord);
    }//GEN-LAST:event_formMouseDragged

    private void btnCerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarAplicacionActionPerformed
        confirmarSalida(true);
    }//GEN-LAST:event_btnCerrarAplicacionActionPerformed

    private void btnOpcionAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionAdministrarActionPerformed
        btnOpcionAdministrar.setForeground(COLOR);
        btnOpcionBuscar.setForeground(Color.WHITE);
        btnOpcionRegistro.setForeground(Color.WHITE);
        btnOpcionInicio.setForeground(Color.WHITE);
        btnOpcionReporte.setForeground(Color.WHITE);
       
        mainViewFrame.removeAll();
        mainViewFrame.add(new panelAdministrar(this, usuario));
        mainViewFrame.validate();

    }//GEN-LAST:event_btnOpcionAdministrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Principal(null).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarAplicacion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnOpcionAdministrar;
    private javax.swing.JButton btnOpcionBuscar;
    private javax.swing.JButton btnOpcionInicio;
    private javax.swing.JButton btnOpcionRegistro;
    private javax.swing.JButton btnOpcionReporte;
    private javax.swing.JPanel infoColorUsario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainViewFrame;
    // End of variables declaration//GEN-END:variables
}
